import Head from "next/head"
import Image from "next/image"

export default function Home() {
  return (
    <div>
      <Head>
        <title>MY.NOTES</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className="text-bold text-3xl">MY.NOTES</main>
    </div>
  )
}
